---
- name: Coletar infos das máquinas
  hosts: all
  gather_facts: yes
  tasks:

    - name: Infos básicas
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          CPU: {{ ansible_processor_vcpus }} vCPUs - {{ ansible_processor[1] }}
          RAM: {{ ansible_memtotal_mb }} MB
          Disco Root: {{ ansible_mounts | selectattr('mount','equalto','/') | map(attribute='size_total') | first | int // 1024 // 1024 }} MB          

    - name: Containers Docker rodando
      shell: docker ps
      register: docker_ps
      ignore_errors: yes

    - name: Mostrar containers
      debug:
        msg: "{{ docker_ps.stdout | default('Nenhum container rodando ou docker não instalado') }}"

    - name: Uso de disco do Docker
      shell: docker system df
      register: docker_df
      ignore_errors: yes

    - name: Mostrar uso de disco do Docker
      debug:
        msg: "{{ docker_df.stdout | default('Docker não instalado ou sem dados') }}"
